Reduce pod deployment

diff --git a/helm_deploy/wordpress/templates/deployment.yaml b/helm_deploy/wordpress/templates/deployment.yaml
--- a/helm_deploy/wordpress/templates/deployment.yaml
+++ b/helm_deploy/wordpress/templates/deployment.yaml
@@ -52,22 +52,22 @@ spec:
             - secretRef:
                 name: hale-wp-secrets-{{ .Release.Revision }}
 {{- if or (eq .Values.configmap.envtype "prod") (eq .Values.configmap.envtype "staging") }}
-          livenessProbe:
-            exec:
-              command:
-              - sh
-              - -c
-              - |
-                if [ -f /var/www/html/wp-load.php ]; then
-                  exit 0
-                else
-                  exit 1
-                fi
-            initialDelaySeconds: 120
-            periodSeconds: 10
-            timeoutSeconds: 5
-            failureThreshold: 6
-            successThreshold: 1
+          # livenessProbe:
+          #   exec:
+          #     command:
+          #     - sh
+          #     - -c
+          #     - |
+          #       if [ -f /var/www/html/wp-load.php ]; then
+          #         exit 0
+          #       else
+          #         exit 1
+          #       fi
+          #   initialDelaySeconds: 120
+          #   periodSeconds: 10
+          #   timeoutSeconds: 5
+          #   failureThreshold: 6
+          #   successThreshold: 1
           readinessProbe:
             exec:
               command:
